"""
compress_fs.py — PlatformIO extra script  (pre:scripts/compress_fs.py)

Runs at *configuration* time (before any build targets are set up) so that:

1. Gzip-compresses every file from $PROJECT_DATA_DIR (data/) into
       .pio/build/<env>/gz_data/<file>.gz
   and redirects PROJECT_DATA_DIR so mklittlefs builds the FS image
   from the compressed files.

2. Generates  src/webfiles.h  — a C header with every compressed file
   as a  static const uint8_t[]  ROM array.  webserver.cpp includes
   this header and serves static content directly from flash with zero
   heap allocation per request.  This eliminates the OOM crashes caused
   by multiple concurrent AsyncFileResponse / malloc buffers competing
   for the limited ESP32 heap.

   Array naming: dots, dashes and slashes in the filename become
   underscores, prefixed with  wf_.
   Example:  index.html  →  wf_index_html / wf_index_html_size
"""

Import("env")  # noqa: F821  (injected by SCons / PlatformIO)

import gzip
import shutil
from pathlib import Path

# ── Resolve paths ──────────────────────────────────────────────────────────
src     = Path(env.subst("$PROJECT_DATA_DIR"))   # normally  <project>/data
dst     = Path(env.subst("$BUILD_DIR")) / "gz_data"
hdr_out = Path(env.subst("$PROJECT_SRC_DIR")) / "webfiles.h"

if not src.is_dir():
    pass
else:
    # ── (Re)create output directory ────────────────────────────────────────
    if dst.exists():
        shutil.rmtree(dst)
    dst.mkdir(parents=True)

    # ── Compress every file + collect data for the C header ───────────────
    # En WSL/NTFS aparecen ADS "<file>:Zone.Identifier" como archivos. Si los
    # procesamos se generan identificadores con ':' en webfiles.h (C inválido).
    def _skip(p: Path) -> bool:
        name = p.name
        return (":" in name) or name.endswith(".Identifier") or name.startswith(".")

    entries = []   # list of (ident, gz_bytes) tuples
    total_in = total_out = 0
    for f in sorted(src.rglob("*")):
        if not f.is_file() or _skip(f):
            continue
        rel  = f.relative_to(src)
        out  = dst / (str(rel) + ".gz")
        out.parent.mkdir(parents=True, exist_ok=True)
        raw  = f.read_bytes()
        gz   = gzip.compress(raw, compresslevel=9)
        out.write_bytes(gz)
        total_in  += len(raw)
        total_out += len(gz)
        pct = 100 * (1 - len(gz) / len(raw)) if raw else 0
        print(f"  [compress_fs]  {str(rel):<42}  {len(raw):>7} → {len(gz):>6} B  ({pct:.0f}%)")

        ident = str(rel).replace("\\", "_").replace("/", "_") \
                        .replace(".", "_").replace("-", "_")
        entries.append((ident, gz))

    if total_in:
        pct_t = 100 * (1 - total_out / total_in)
        print(f"  [compress_fs]  Total  {total_in:>7} → {total_out:>6} B  ({pct_t:.0f}% saved)")

    # ── Generate src/webfiles.h ───────────────────────────────────────────
    # Binary image formats must be served without Content-Encoding so browsers
    # render transparency correctly.  Text/script files use gzip when it helps.
    NO_GZ_EXTS = {".png", ".ico", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".woff", ".woff2"}

    with open(str(hdr_out), "w", newline="\n") as h:
        h.write("// Auto-generated by scripts/compress_fs.py — do not edit\n")
        h.write("#pragma once\n#include <stdint.h>\n#include <stddef.h>\n#include <stdbool.h>\n\n")
        for f in sorted(src.rglob("*")):
            if not f.is_file() or _skip(f):
                continue
            rel   = f.relative_to(src)
            ident = str(rel).replace("\\", "_").replace("/", "_") \
                            .replace(".", "_").replace("-", "_")
            raw   = f.read_bytes()
            gz    = gzip.compress(raw, compresslevel=9)
            force_raw = f.suffix.lower() in NO_GZ_EXTS
            if not force_raw and len(gz) < len(raw):
                payload, is_gz = gz,  "true"
            else:
                payload, is_gz = raw, "false"
            hex_vals = ", ".join(f"0x{b:02x}" for b in payload)
            h.write(f"static const uint8_t wf_{ident}[] = {{{hex_vals}}};\n")
            h.write(f"static const size_t  wf_{ident}_size    = {len(payload)};\n")
            h.write(f"static const bool    wf_{ident}_gzipped = {is_gz};\n\n")
    print(f"  [compress_fs]  C header  → {hdr_out}  ({len(entries)} files)")

    # ── Redirect the FS build to the compressed folder ─────────────────────
    env.Replace(PROJECT_DATA_DIR=str(dst))
    print(f"  [compress_fs]  FS image will be built from {dst}")
