#!/usr/bin/env python3
"""
compress_fs.py — standalone web asset embedder.

Reads every file under <project>/data/ and writes <project>/main/webfiles.h:
a C header containing each asset as a static const uint8_t[] array, gzipped
when that shrinks the file (and the file is not a binary image type that
browsers expect raw).

Run before each build (driven from the top-level CMakeLists.txt).
Idempotent — overwrites the header every time.

Array naming: dots, dashes and slashes in the filename become underscores,
prefixed with wf_.  Example: index.html -> wf_index_html / wf_index_html_size.
"""

import gzip
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR     = PROJECT_ROOT / "data"
HDR_OUT      = PROJECT_ROOT / "main" / "webfiles.h"

# Binary image / font formats served without Content-Encoding so browsers
# render them correctly.  Everything else is gzipped when that helps.
NO_GZ_EXTS = {".png", ".ico", ".jpg", ".jpeg", ".gif", ".webp", ".bmp",
              ".woff", ".woff2"}


def _skip(p: Path) -> bool:
    """Skip Windows-ADS (foo:Zone.Identifier), dotfiles, etc."""
    name = p.name
    return (":" in name) or name.endswith(".Identifier") or name.startswith(".")


def _ident(rel: Path) -> str:
    return str(rel).replace("\\", "_").replace("/", "_") \
                   .replace(".", "_").replace("-", "_")


def main() -> int:
    if not DATA_DIR.is_dir():
        print(f"[compress_fs] {DATA_DIR} does not exist — skipping", file=sys.stderr)
        return 0

    HDR_OUT.parent.mkdir(parents=True, exist_ok=True)

    total_in = total_out = 0
    files = sorted(p for p in DATA_DIR.rglob("*") if p.is_file() and not _skip(p))

    with open(HDR_OUT, "w", newline="\n") as h:
        h.write("// Auto-generated by scripts/compress_fs.py — do not edit\n")
        h.write("#pragma once\n#include <stdint.h>\n#include <stddef.h>\n"
                "#include <stdbool.h>\n\n")
        for f in files:
            rel   = f.relative_to(DATA_DIR)
            ident = _ident(rel)
            raw   = f.read_bytes()
            gz    = gzip.compress(raw, compresslevel=9)

            force_raw = f.suffix.lower() in NO_GZ_EXTS
            if not force_raw and len(gz) < len(raw):
                payload, is_gz = gz, "true"
            else:
                payload, is_gz = raw, "false"

            total_in  += len(raw)
            total_out += len(payload)
            pct = 100 * (1 - len(payload) / len(raw)) if raw else 0
            print(f"  [compress_fs]  {str(rel):<42}  {len(raw):>7} -> "
                  f"{len(payload):>6} B  ({pct:.0f}%)")

            hex_vals = ", ".join(f"0x{b:02x}" for b in payload)
            h.write(f"static const uint8_t wf_{ident}[] = {{{hex_vals}}};\n")
            h.write(f"static const size_t  wf_{ident}_size    = {len(payload)};\n")
            h.write(f"static const bool    wf_{ident}_gzipped = {is_gz};\n\n")

    if total_in:
        pct_t = 100 * (1 - total_out / total_in)
        print(f"  [compress_fs]  Total  {total_in:>7} -> "
              f"{total_out:>6} B  ({pct_t:.0f}% saved)")
    print(f"  [compress_fs]  Header   -> {HDR_OUT}  ({len(files)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
