#!/usr/bin/env python3
"""
Convert the TruMinus logo PNG to a C header (RGB565 little-endian) for LVGL.

Usage (from the project root):
    python scripts/gen_logo.py                           # defaults below
    python scripts/gen_logo.py data/truminus-logo.png src/logo_rgb565.h

Requirements:
    pip install Pillow
"""
import sys
from pathlib import Path
from PIL import Image

# ── configurable ──────────────────────────────────────────────────────────────
TARGET_H   = 31          # max height in px (status bar = 35 px, 2 px margin each side)
# Background colour to alpha-blend against (C_BG from cyddisplay.cpp: 0x1a1a2e)
BG = (0x1a, 0x1a, 0x2e)
# ─────────────────────────────────────────────────────────────────────────────

SRC_DEFAULT = Path("src/truminus-logo-transparent.png")
DST_DEFAULT = Path("src/truminus-logo-transparent_rgb565.h")


def to_rgb565_le(r: int, g: int, b: int) -> int:
    """Pack 8-bit RGB components into a 16-bit RGB565 little-endian word."""
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main() -> None:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else SRC_DEFAULT
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else DST_DEFAULT

    if not src.exists():
        sys.exit(f"[gen_logo] Source not found: {src}")

    img = Image.open(src).convert("RGBA")
    orig_w, orig_h = img.size

    # Scale to TARGET_H, keep aspect ratio
    new_h = min(orig_h, TARGET_H)
    new_w = max(1, round(orig_w * new_h / orig_h))
    img = img.resize((new_w, new_h), Image.LANCZOS)

    # Convert pixels → RGB565 LE bytes, alpha-blended against BG
    data: list[int] = []
    for py in range(new_h):
        for px in range(new_w):
            r, g, b, a = img.getpixel((px, py))
            if a < 255:
                r = (r * a + BG[0] * (255 - a)) // 255
                g = (g * a + BG[1] * (255 - a)) // 255
                b = (b * a + BG[2] * (255 - a)) // 255
            word = to_rgb565_le(r, g, b)
            data.append(word & 0xFF)          # low byte first (little-endian)
            data.append((word >> 8) & 0xFF)

    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/gen_logo.py — DO NOT EDIT.\n")
        f.write(f"// Source : {src.name}  ({orig_w}x{orig_h} px)\n")
        f.write(f"// Output : {new_w}x{new_h} px, RGB565 little-endian\n")
        f.write(f"// BG blend: 0x{BG[0]:02x}{BG[1]:02x}{BG[2]:02x}\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"static constexpr int LOGO_W = {new_w};\n")
        f.write(f"static constexpr int LOGO_H = {new_h};\n\n")
        f.write(f"// {new_w * new_h * 2} bytes\n")
        f.write(f"static const uint8_t LOGO_RGB565[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n")

    print(f"[gen_logo] {src.name}  {orig_w}x{orig_h}  →  {new_w}x{new_h}  "
          f"({len(data)} bytes)  →  {dst}")


if __name__ == "__main__":
    main()
