#!/usr/bin/env python3
"""
gen_symbols.py — Generate src/symbols_14.c for LVGL (v8/v9)

Renders fa-tint (U+F043) and fa-thermometer-half (U+F2C7) from the
FontAwesome WOFF that gen_symbols.ps1 already downloaded.

Requirements (install once):
    pip install freetype-py

Usage (from the project root):
    python scripts/gen_symbols.py
"""

import sys, os, math
from pathlib import Path

try:
    import freetype
except ImportError:
    sys.exit(
        "Missing dependency: freetype-py\n"
        "Install with:  pip install freetype-py"
    )

# ── Config ────────────────────────────────────────────────────────────────────
GLYPHS = [
    (0xF043, "fa-tint"),
    (0xF2C9, "fa-thermometer-half"),
]
SIZE      = 14          # px — must match what cyddisplay.cpp uses
BPP       = 4           # bits per pixel
LINE_H    = SIZE        # total line height in px
BASE_LINE = 3           # px below baseline included in line height
WOFF      = Path("scripts/fonts/FontAwesome5-Solid+Brands+Regular.woff")
OUT       = Path("src/symbols_14.c")
# ─────────────────────────────────────────────────────────────────────────────

def to4bpp(buf: bytes, w: int, h: int, pitch: int) -> bytes:
    """Convert FreeType 8bpp grayscale bitmap to 4bpp packed (LVGL format)."""
    out = []
    for row in range(h):
        base = row * pitch
        nibbles = [buf[base + col] >> 4 for col in range(w)]
        for i in range(0, w, 2):
            hi = nibbles[i]
            lo = nibbles[i + 1] if i + 1 < w else 0
            out.append((hi << 4) | lo)
    return bytes(out)

def render(face: freetype.Face, cp: int):
    """Render one glyph. Returns (bitmap_4bpp, box_w, box_h, adv_w_q4, ofs_x, ofs_y)."""
    face.set_pixel_sizes(0, SIZE)
    face.load_char(cp, freetype.FT_LOAD_RENDER)
    g   = face.glyph
    bm  = g.bitmap
    w, h = bm.width, bm.rows
    adv_w_q4 = round((g.advance.x >> 6) * 16)   # pixels → 8.4 fixed-point
    ofs_x    = g.bitmap_left
    ofs_y    = g.bitmap_top - h                   # bottom of bbox from baseline
    return to4bpp(bytes(bm.buffer), w, h, bm.pitch), w, h, adv_w_q4, ofs_x, ofs_y

def main():
    if not WOFF.exists():
        sys.exit(
            f"Font not found: {WOFF}\n"
            "Run scripts/gen_symbols.ps1 first to download it."
        )

    print(f"[gen_symbols] Loading {WOFF.name}...")
    # Modern FreeType (shipped with freetype-py wheels) reads WOFF natively.
    face = freetype.Face(str(WOFF))

    rendered = []
    for cp, name in GLYPHS:
        bm, w, h, adv, ox, oy = render(face, cp)
        rendered.append((cp, name, bm, w, h, adv, ox, oy))
        print(f"  U+{cp:04X}  {name:30s}  {w}x{h}  adv={adv/16:.1f}px  ofs=({ox},{oy})")

    # ── Build C file ──────────────────────────────────────────────────────────
    OUT.parent.mkdir(parents=True, exist_ok=True)
    L = []
    def a(s=""): L.append(s)

    a("/*")
    a(" * symbols_14.c — generated by scripts/gen_symbols.py  DO NOT EDIT")
    glyphs_str = ", ".join(f"U+{cp:04X} {n}" for cp, n, *_ in rendered)
    a(f" * Glyphs : {glyphs_str}")
    a(f" * Size   : {SIZE}px   BPP: {BPP}")
    a(" */")
    a()
    a('#include "lvgl.h"')
    a()
    a("// Fallback: regular characters not found in this font are looked up in montserrat_14")
    a("LV_FONT_DECLARE(lv_font_montserrat_14);")
    a()
    a("#ifndef LV_ATTRIBUTE_MEM_ALIGN")
    a("#define LV_ATTRIBUTE_MEM_ALIGN")
    a("#endif")
    a()

    # Bitmap data
    a("static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
    bitmap_offsets = []
    offset = 0
    for cp, name, bm, w, h, adv, ox, oy in rendered:
        bitmap_offsets.append(offset)
        a(f"    /* U+{cp:04X}  {name} */")
        for i in range(0, len(bm), 16):
            chunk = bm[i:i+16]
            a("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        offset += len(bm)
    a("};")
    a()

    # Glyph descriptors (index 0 = empty placeholder)
    a("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    a("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},")
    for i, (cp, name, bm, w, h, adv, ox, oy) in enumerate(rendered):
        a(f"    {{.bitmap_index = {bitmap_offsets[i]:5d}, .adv_w = {adv:4d},"
          f" .box_w = {w:3d}, .box_h = {h:3d}, .ofs_x = {ox:3d}, .ofs_y = {oy:3d}}},  /* U+{cp:04X} */")
    a("};")
    a()

    # CMaps — one FORMAT0_TINY entry per glyph (the codepoints are far apart)
    a("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    for i, (cp, name, *_) in enumerate(rendered):
        a(f"    {{  /* U+{cp:04X}  {name} */")
        a(f"        .range_start = 0x{cp:04X}, .range_length = 1, .glyph_id_start = {i+1},")
        a( "        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,")
        a( "        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY")
        a( "    },")
    a("};")
    a()

    # Font format descriptor
    a("static lv_font_fmt_txt_dsc_t font_dsc = {")
    a("    .glyph_bitmap = glyph_bitmap,")
    a("    .glyph_dsc    = glyph_dsc,")
    a("    .cmaps        = cmaps,")
    a("    .kern_dsc     = NULL,")
    a("    .kern_scale   = 0,")
    a(f"    .cmap_num     = {len(rendered)},")
    a(f"    .bpp          = {BPP},")
    a("    .kern_classes = 0,")
    a("    .bitmap_format = 0,")
    a("};")
    a()

    # Font object (extern so LV_FONT_DECLARE can reference it)
    a("const lv_font_t symbols_14 = {")
    a("    .get_glyph_dsc    = lv_font_get_glyph_dsc_fmt_txt,")
    a("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    a(f"    .line_height      = {LINE_H},")
    a(f"    .base_line        = {BASE_LINE},")
    a("    .subpx            = LV_FONT_SUBPX_NONE,")
    a("    .underline_position  = -1,")
    a("    .underline_thickness = 1,")
    a("    .dsc              = &font_dsc,")
    a("    .fallback         = &lv_font_montserrat_14,")
    a("    .user_data        = NULL,")
    a("};")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    total_bytes = sum(len(r[2]) for r in rendered)
    print(f"[gen_symbols] Written {OUT}  ({total_bytes} bytes of bitmap data)")

if __name__ == "__main__":
    main()
