#ifdef CYD
#include "cyddisplay.hpp"
#include <esp32_smartdisplay.h>
#include <WiFi.h>
#include <Preferences.h>
#include "wifisetup.hpp"
#include "truminus-logo-transparent_rgb565.h"   // generated by scripts/gen_logo.py

// ── Símbolos FontAwesome extra (generados por scripts/gen_symbols.ps1) ───────
LV_FONT_DECLARE(symbols_14);
#define MY_SYMBOL_THERMOMETER "\xEF\x80\x95"   // U+F015  fa-home (temperatura ambiente)
#define MY_SYMBOL_TINT        "\xEF\x81\x83"   // U+F043  fa-tint
#define MY_SYMBOL_FIRE        "\xEF\x81\xAD"   // U+F06D  fa-fire (calefacción activa)
#define MY_SYMBOL_THERM_EXT   "\xEF\x8B\x89"   // U+F2C9  fa-thermometer-half (temperatura exterior)
#define MY_SYMBOL_CHEVRON_R   "\xEF\x81\x94"   // U+F054  fa-chevron-right

// ═══════════════════════════════════════════════════════════════════════════
// Paleta
// ═══════════════════════════════════════════════════════════════════════════
#define C_BG         0x1a1a2e
#define C_TOPBAR     0x0f0f22
#define C_SEP        0x444466
#define C_LABEL      0x8888aa
#define C_BTN_OFF    0x2a2a4a
#define C_BTN_ON     0x3a7bd5
#define C_HEAT_ON    0x1a8a3a
#define C_TEXT       0xffffff
#define C_WIFI_OK    0x44ff44
#define C_WIFI_NO    0xff4444
#define C_WIFI_CONN  0xffaa00
#define C_MQTT_OK    0x44ffaa
#define C_MQTT_NO    0xff8800
#define C_MQTT_DIS   0x666688

// ═══════════════════════════════════════════════════════════════════════════
// Layout  (320×240 landscape)
// ═══════════════════════════════════════════════════════════════════════════
//  y=0..27    Barra superior (28px)
//  y=28       Separador horizontal
//  y=29..203  Contenido (175px)
//  y=204      Separador horizontal
//  y=205..239 Barra de estado (35px)
//
//  x=0..152   Panel izquierdo  CALEFACCIÓN  (153px)
//  x=153      Separador vertical
//  x=154..319 Panel derecho    AGUA CALIENTE (166px)

#define Y_TOP_H   28
#define Y_SEP1    28
#define Y_CONT    29
#define Y_SEP2    204
#define Y_STAT    205
#define CONT_H    (Y_SEP2 - Y_CONT)   // 175

#define X_DIV     153          // separador vertical
#define X_R       154          // inicio panel derecho
#define W_L       153          // ancho panel izquierdo
#define W_R       166          // ancho panel derecho

// ═══════════════════════════════════════════════════════════════════════════
// Valores de modos
// ═══════════════════════════════════════════════════════════════════════════
static const int   BOILER_N = 4;
static const char* BOILER_STR[BOILER_N] = {"off",   "eco",           "high",          "boost"};
static const char* BOILER_LAB[BOILER_N] = {"Apag.", "40\xc2\xb0""C", "60\xc2\xb0""C", "60\xc2\xb0""C " LV_SYMBOL_CHARGE};

static const int   FAN_N      = 3;
static const int   FAN_HEAT_N = 2;  // sólo Eco/Alto con calefacción ON
static const char* FAN_STR[FAN_N]  = {"eco", "high", "off"};
static const char* FAN_LAB[FAN_N]  = {"Eco", "Alto", "Apag."};

// Energía — mapea índice de dropdown a TEnergySelection del LIN bus
// 0=EsGasDiesel, 1=EsMixed900 (850W), 2=EsMixed800 (1700W),
// 3=EsElectro900 (850W), 4=EsElectro1800 (1700W)
static const char* ENERGY_OPTS =
    "Gas\n"
    "Gas + Elec. 850 W\n"
    "Gas + Elec. 1700 W\n"
    "Elec. 850 W\n"
    "Elec. 1700 W";

// ═══════════════════════════════════════════════════════════════════════════
// Punteros a settings
// ═══════════════════════════════════════════════════════════════════════════
static TTempSetting*   s_roomSp  = nullptr;
static TBoilerSetting* s_waterSp = nullptr;
static TOnOffSetting*  s_heatOn  = nullptr;
static TFanSetting*    s_fanMode = nullptr;

// ═══════════════════════════════════════════════════════════════════════════
// Estado interno
// ═══════════════════════════════════════════════════════════════════════════
static int s_fanLevel   = 5;   // nivel numérico ventilación sin calefacción (1-10)
static int s_energyMode = 0;   // índice TEnergySelection activo (0-4)

// ═══════════════════════════════════════════════════════════════════════════
// Handles de widgets
// ═══════════════════════════════════════════════════════════════════════════
static lv_obj_t* s_scr          = nullptr;

// Barra superior
static lv_obj_t* s_ambLbl       = nullptr;
static lv_obj_t* s_aguaLbl      = nullptr;
static lv_obj_t* s_fireLbl      = nullptr;   // icono llama — parpadea cuando calefacción activa
static lv_obj_t* s_extLbl       = nullptr;   // temperatura exterior (AM2301)
static lv_obj_t* s_wifiDot      = nullptr;
static lv_obj_t* s_mqttDot      = nullptr;
static lv_obj_t* s_linDot       = nullptr;

// Panel izquierdo — Calefacción
static lv_obj_t* s_heatBtn      = nullptr;
static lv_obj_t* s_heatBtnLbl   = nullptr;
static lv_obj_t* s_spRow        = nullptr;   // fila setpoint
static lv_obj_t* s_spLbl        = nullptr;   // valor "22.0°C"

// Panel izquierdo — Ventilador
static lv_obj_t* s_fanHeatingRow = nullptr;  // fila eco/alto/apag (calef. ON)
static lv_obj_t* s_fanOffRow     = nullptr;  // fila On/Off          (calef. OFF)
static lv_obj_t* s_fanLevelRow   = nullptr;  // fila ↓ nivel ↑       (calef. OFF + On)
static lv_obj_t* s_fanBtn[FAN_N];            // botones eco/alto/apag
static lv_obj_t* s_fanOnBtn      = nullptr;
static lv_obj_t* s_fanOffBtn     = nullptr;
static lv_obj_t* s_fanLevelLbl   = nullptr;

// Panel derecho — Agua caliente + Energía
static lv_obj_t* s_boilerBtn[BOILER_N];
static lv_obj_t* s_energyDd      = nullptr;

// Barra de estado
static lv_obj_t* s_statusLbl    = nullptr;
static lv_obj_t* s_ipLbl        = nullptr;

// ── Backlight fade (tarea FreeRTOS dedicada) ─────────────────────────────
// blFadeTo() se puede llamar desde cualquier contexto; la tarea mueve el
// brillo actual hacia el objetivo a 0.04 por tick (20 ms) → fade de 500 ms
// para el rango completo 0→1 ó 1→0.
static volatile float s_blCurrent = 1.0f;
static volatile float s_blTarget  = 1.0f;

static void blFadeTo(float target) {
    s_blTarget = target;
}

static void backlightTask(void* /*arg*/) {
    // 25 pasos × 20 ms = 500 ms para recorrer el rango completo (0.0 → 1.0)
    const TickType_t TICK    = pdMS_TO_TICKS(20);
    const float      STEP    = 1.0f / 25.0f;   // 0.04 por tick
    for (;;) {
        float cur = s_blCurrent;
        float tgt = s_blTarget;
        if (cur != tgt) {
            float delta = tgt - cur;
            float step  = (delta > 0.0f)
                          ? ((delta < STEP) ? delta :  STEP)
                          : ((delta > -STEP) ? delta : -STEP);
            cur += step;
            if (cur < 0.0f) cur = 0.0f;
            if (cur > 1.0f) cur = 1.0f;
            s_blCurrent = cur;
            smartdisplay_lcd_set_backlight(cur);
        }
        vTaskDelay(TICK);
    }
}

// ── Configuración / apagado de pantalla ──────────────────────────────────
static volatile CydNavRequest s_navRequest = CydNavRequest::None;

static const uint32_t TIMEOUT_MS[]    = { 30000, 60000, 180000, 0 };
static const char*    TIMEOUT_LABEL[] = { "30 segundos", "1 minuto", "3 minutos", "No apagar" };
static const int      TIMEOUT_N       = 4;
static int       s_timeoutIdx  = 0;       // índice activo (0 = 30 s)
static bool      s_screenOff   = false;
static bool      s_screenDimmed = false;  // en aviso de apagado (brillo 30 %)
static lv_obj_t* s_wakeOverlay  = nullptr;
static lv_obj_t* s_settingsScr  = nullptr;
static lv_obj_t* s_displayScr   = nullptr;
static lv_obj_t* s_dispOptBtn[TIMEOUT_N] = {};

// Declaraciones adelantadas (se llaman mutuamente entre callbacks)
static void showSettingsMenu();
static void showDisplaySettings();

// ═══════════════════════════════════════════════════════════════════════════
// Logo
// ═══════════════════════════════════════════════════════════════════════════
static uint16_t* s_logoBuf = nullptr;

// Coloca el logo (ya cargado en s_logoBuf) en la barra de estado.
static void placeLogoInStatusBar(lv_obj_t* scr) {
    if (!s_logoBuf) return;
    lv_obj_t* canvas = lv_canvas_create(scr);
    lv_canvas_set_buffer(canvas, s_logoBuf, LOGO_W, LOGO_H,
                         LV_COLOR_FORMAT_RGB565);
    lv_obj_set_size(canvas, LOGO_W, LOGO_H);
    lv_obj_align(canvas, LV_ALIGN_BOTTOM_RIGHT, -2, -2);
    lv_obj_clear_flag(canvas, LV_OBJ_FLAG_CLICKABLE);
}

// Muestra el logo centrado en pantalla durante ms milisegundos (splash).
// Aloja s_logoBuf una sola vez; lo reutiliza después en la barra de estado.
static void showSplash(uint32_t ms) {
    s_logoBuf = (uint16_t*)malloc(LOGO_W * LOGO_H * 2);
    if (!s_logoBuf) { Serial.println("[logo] OOM"); return; }
    memcpy(s_logoBuf, LOGO_RGB565, LOGO_W * LOGO_H * 2);

    lv_obj_t* splash = lv_obj_create(NULL);
    lv_obj_remove_style_all(splash);
    lv_obj_set_style_bg_color(splash, lv_color_hex(C_BG),  LV_PART_MAIN);
    lv_obj_set_style_bg_opa (splash, LV_OPA_COVER,         LV_PART_MAIN);
    lv_obj_clear_flag(splash, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));

    lv_obj_t* canvas = lv_canvas_create(splash);
    lv_canvas_set_buffer(canvas, s_logoBuf, LOGO_W, LOGO_H,
                         LV_COLOR_FORMAT_RGB565);
    lv_obj_set_size(canvas, LOGO_W, LOGO_H);
    lv_obj_align(canvas, LV_ALIGN_CENTER, 0, 0);
    lv_obj_clear_flag(canvas, LV_OBJ_FLAG_CLICKABLE);

    lv_screen_load(splash);

    uint32_t t0 = millis();
    while (millis() - t0 < ms) {
        lv_task_handler();
        delay(5);
    }

    lv_obj_delete(splash);   // elimina splash + canvas; s_logoBuf permanece válido
    Serial.printf("[logo] splash %dx%d px (%d bytes)\n", LOGO_W, LOGO_H, LOGO_W * LOGO_H * 2);
}

// ═══════════════════════════════════════════════════════════════════════════
// Helpers de construcción
// ═══════════════════════════════════════════════════════════════════════════
static lv_obj_t* makeBtn(lv_obj_t* parent,
                          int x, int y, int w, int h,
                          const char* txt,
                          lv_event_cb_t cb, void* udata = nullptr,
                          lv_obj_t** outLbl = nullptr) {
    lv_obj_t* btn = lv_btn_create(parent);
    lv_obj_set_pos(btn, x, y);
    lv_obj_set_size(btn, w, h);
    lv_obj_set_style_bg_color(btn, lv_color_hex(C_BTN_OFF), LV_PART_MAIN);
    lv_obj_set_style_bg_color(btn, lv_color_hex(C_BTN_ON),  LV_STATE_PRESSED);
    lv_obj_set_style_radius(btn, 5, LV_PART_MAIN);
    lv_obj_set_style_border_width(btn, 0, LV_PART_MAIN);
    lv_obj_set_style_shadow_width(btn, 0, LV_PART_MAIN);
    if (cb) lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, udata);

    lv_obj_t* lbl = lv_label_create(btn);
    lv_label_set_text(lbl, txt);
    lv_obj_set_style_text_color(lbl, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_font(lbl, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_center(lbl);
    if (outLbl) *outLbl = lbl;
    return btn;
}

// Contenedor transparente usado para agrupar y ocultar filas de botones
static lv_obj_t* makeRow(lv_obj_t* parent, int x, int y, int w, int h) {
    lv_obj_t* row = lv_obj_create(parent);
    lv_obj_remove_style_all(row);
    lv_obj_set_pos(row, x, y);
    lv_obj_set_size(row, w, h);
    lv_obj_set_style_bg_opa(row, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_clear_flag(row, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));
    return row;
}

static void makeSep(lv_obj_t* parent, int x, int y, int w, int h) {
    lv_obj_t* sep = lv_obj_create(parent);
    lv_obj_remove_style_all(sep);
    lv_obj_set_pos(sep, x, y);
    lv_obj_set_size(sep, w, h);
    lv_obj_set_style_bg_color(sep, lv_color_hex(C_SEP), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(sep, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_clear_flag(sep, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));
}

static lv_obj_t* makeSecLabel(lv_obj_t* parent, int x, int y, const char* txt) {
    lv_obj_t* lbl = lv_label_create(parent);
    lv_obj_set_style_text_font(lbl, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(lbl, lv_color_hex(C_LABEL), LV_PART_MAIN);
    lv_label_set_text(lbl, txt);
    lv_obj_set_pos(lbl, x, y);
    return lbl;
}

// ═══════════════════════════════════════════════════════════════════════════
// refreshControls — actualiza colores y visibilidad según estado
// ═══════════════════════════════════════════════════════════════════════════
static void refreshControls() {
    if (!s_heatOn || !s_roomSp || !s_waterSp || !s_fanMode) return;

    bool heat   = (s_heatOn->getIntValue() != 0);
    int  fanVal = s_fanMode->getIntValue();   // -1=eco, -2=high, 0=off, 1-10=numérico

    // ── Calefacción ──────────────────────────────────────────────────────
    lv_label_set_text(s_heatBtnLbl, heat ? "ENCENDIDO" : "APAGADO");
    lv_obj_set_style_bg_color(s_heatBtn,
        lv_color_hex(heat ? C_HEAT_ON : C_BTN_OFF), LV_PART_MAIN);

    // ── Setpoint de temperatura ──────────────────────────────────────────
    if (heat) {
        lv_obj_remove_flag(s_spRow, LV_OBJ_FLAG_HIDDEN);
        char buf[12];
        snprintf(buf, sizeof(buf), "%.1f\xc2\xb0""C", s_roomSp->getFloatValue());
        lv_label_set_text(s_spLbl, buf);
    } else {
        lv_obj_add_flag(s_spRow, LV_OBJ_FLAG_HIDDEN);
    }

    // ── Ventilador ───────────────────────────────────────────────────────
    if (heat) {
        // Modo calefacción: 3 botones de nivel de ventilador
        lv_obj_remove_flag(s_fanHeatingRow, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(s_fanOffRow,    LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(s_fanLevelRow,  LV_OBJ_FLAG_HIDDEN);

        String fanStr = s_fanMode->getStringValue();
        for (int i = 0; i < FAN_HEAT_N; i++) {
            lv_obj_set_style_bg_color(s_fanBtn[i],
                lv_color_hex((fanStr == FAN_STR[i]) ? C_BTN_ON : C_BTN_OFF),
                LV_PART_MAIN);
        }
    } else {
        // Modo apagado: On/Off + control de nivel
        lv_obj_add_flag(s_fanHeatingRow, LV_OBJ_FLAG_HIDDEN);
        lv_obj_remove_flag(s_fanOffRow,  LV_OBJ_FLAG_HIDDEN);

        bool fanOn = (fanVal != 0);   // cualquier valor ≠ 0 = ventilación activa
        // El Truma ignora comandos de ventilador mientras el boiler está calentando.
        // Deshabilitar controles para evitar cambios accidentales que se aplicarían
        // al siguiente ciclo del boiler.
        bool boilerActive = (s_waterSp && s_waterSp->getStringValue() != "off");

        // Sincronizar s_fanLevel si el valor actual es numérico
        if (fanVal > 0) s_fanLevel = fanVal;

        // Mostrar fila de nivel sólo si ventilador está on Y boiler no activo
        if (fanOn && !boilerActive) {
            lv_obj_remove_flag(s_fanLevelRow, LV_OBJ_FLAG_HIDDEN);
        } else {
            lv_obj_add_flag(s_fanLevelRow, LV_OBJ_FLAG_HIDDEN);
        }

        if (boilerActive) {
            lv_obj_add_state(s_fanOnBtn,  LV_STATE_DISABLED);
            lv_obj_add_state(s_fanOffBtn, LV_STATE_DISABLED);
        } else {
            lv_obj_remove_state(s_fanOnBtn,  LV_STATE_DISABLED);
            lv_obj_remove_state(s_fanOffBtn, LV_STATE_DISABLED);
        }

        lv_obj_set_style_bg_color(s_fanOnBtn,
            lv_color_hex(fanOn  ? C_BTN_ON : C_BTN_OFF), LV_PART_MAIN);
        lv_obj_set_style_bg_color(s_fanOffBtn,
            lv_color_hex(!fanOn ? C_BTN_ON : C_BTN_OFF), LV_PART_MAIN);

        char buf[4];
        snprintf(buf, sizeof(buf), "%d", s_fanLevel);
        lv_label_set_text(s_fanLevelLbl, buf);
    }

    // ── Caldera / Agua caliente ──────────────────────────────────────────
    String boiler = s_waterSp->getStringValue();
    for (int i = 0; i < BOILER_N; i++) {
        lv_obj_set_style_bg_color(s_boilerBtn[i],
            lv_color_hex((boiler == BOILER_STR[i]) ? C_BTN_ON : C_BTN_OFF),
            LV_PART_MAIN);
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Callbacks
// ═══════════════════════════════════════════════════════════════════════════
static void heatCb(lv_event_t*) {
    if (!s_heatOn) return;
    bool turningOff = (s_heatOn->getIntValue() != 0);
    s_heatOn->setValue(String(turningOff ? "0" : "1"));
    // Al apagar la calefacción, forzar ventilador a off
    if (turningOff && s_fanMode)
        s_fanMode->setValue(String("off"));
    refreshControls();
}

static void spDownCb(lv_event_t*) {
    if (!s_roomSp) return;
    double v = s_roomSp->getFloatValue() - 0.5;
    if (v >= 5.0) s_roomSp->setValue(v);
    refreshControls();
}

static void spUpCb(lv_event_t*) {
    if (!s_roomSp) return;
    double v = s_roomSp->getFloatValue() + 0.5;
    if (v <= 30.0) s_roomSp->setValue(v);
    refreshControls();
}

static void boilerCb(lv_event_t* e) {
    if (!s_waterSp) return;
    int idx = (int)(intptr_t)lv_event_get_user_data(e);
    // Al activar el boiler forzar ventilador a off: el Truma aplica comandos
    // de ventilador pendientes al ciclar, causando arranques inesperados.
    if (idx != 0 && s_fanMode)
        s_fanMode->setValue(String("off"));
    s_waterSp->setValue(String(BOILER_STR[idx]));
    refreshControls();
}

// Ventilador — modo calefacción (eco/alto/apag)
static void fanHeatCb(lv_event_t* e) {
    if (!s_fanMode) return;
    int idx = (int)(intptr_t)lv_event_get_user_data(e);
    s_fanMode->setValue(String(FAN_STR[idx]));
    refreshControls();
}

// Ventilador — modo apagado
static void fanOnCb(lv_event_t*) {
    if (!s_fanMode) return;
    if (s_waterSp && s_waterSp->getStringValue() != "off") return;  // boiler activo
    s_fanMode->setValue(String(s_fanLevel));
    refreshControls();
}

static void fanOffCb(lv_event_t*) {
    if (!s_fanMode) return;
    if (s_waterSp && s_waterSp->getStringValue() != "off") return;  // boiler activo
    s_fanMode->setValue(String("off"));
    refreshControls();
}

static void fanLevelDownCb(lv_event_t*) {
    if (!s_fanMode) return;
    if (s_waterSp && s_waterSp->getStringValue() != "off") return;  // boiler activo
    if (s_fanLevel > 1) {
        s_fanLevel--;
        if (s_fanMode->getIntValue() > 0)
            s_fanMode->setValue(String(s_fanLevel));
        refreshControls();
    }
}

static void fanLevelUpCb(lv_event_t*) {
    if (!s_fanMode) return;
    if (s_waterSp && s_waterSp->getStringValue() != "off") return;  // boiler activo
    if (s_fanLevel < 10) {
        s_fanLevel++;
        if (s_fanMode->getIntValue() > 0)
            s_fanMode->setValue(String(s_fanLevel));
        refreshControls();
    }
}

static void energyDdCb(lv_event_t* e) {
    lv_obj_t* dd = (lv_obj_t*)lv_event_get_target(e);
    s_energyMode = (int)lv_dropdown_get_selected(dd);
    // TODO (main.cpp): leer cydGetEnergyMode() y llamar
    //   energySelectFrame.setEnergySelection((TEnergySelection)s_energyMode);
    //   powerLimitFrame.setPowerLimit((TEnergySelection)s_energyMode);
}

// ═══════════════════════════════════════════════════════════════════════════
// API pública: modo de energía seleccionado (para leer desde main.cpp)
// ═══════════════════════════════════════════════════════════════════════════
int cydGetEnergyMode() { return s_energyMode; }

// Actualiza el dropdown desde fuera (llamar bajo mutex de LVGL).
void cydSetEnergyIdx(int idx) {
    if (idx < 0 || idx > 4) return;
    s_energyMode = idx;
    if (s_energyDd)
        lv_dropdown_set_selected(s_energyDd, (uint16_t)idx);
}

// ═══════════════════════════════════════════════════════════════════════════
// NVS — índice de tiempo de apagado
// ═══════════════════════════════════════════════════════════════════════════
static void loadTimeoutIdx() {
    Preferences p;
    p.begin("cyd", true);
    s_timeoutIdx = p.getInt("timeout_idx", 0);   // 0 = 1 min por defecto
    p.end();
}
static void saveTimeoutIdx() {
    Preferences p;
    p.begin("cyd", false);
    p.putInt("timeout_idx", s_timeoutIdx);
    p.end();
}

// ═══════════════════════════════════════════════════════════════════════════
// Wake-on-touch overlay (en lv_layer_top, encima de cualquier pantalla)
// ═══════════════════════════════════════════════════════════════════════════
static void wakeCb(lv_event_t*) {
    if (!s_screenOff) return;
    blFadeTo(1.0f);
    s_screenOff = false;
    if (s_wakeOverlay) {
        lv_obj_delete(s_wakeOverlay);
        s_wakeOverlay = nullptr;
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// Pantalla «Pantalla» — ajuste de apagado automático
// ═══════════════════════════════════════════════════════════════════════════
static void refreshDisplayOpts() {
    for (int i = 0; i < TIMEOUT_N; i++) {
        if (s_dispOptBtn[i])
            lv_obj_set_style_bg_color(s_dispOptBtn[i],
                lv_color_hex(i == s_timeoutIdx ? C_BTN_ON : C_BTN_OFF),
                LV_PART_MAIN);
    }
}

static void navigateBackFromDisplay() {
    lv_obj_t* old = s_displayScr;
    s_displayScr  = nullptr;
    for (int i = 0; i < TIMEOUT_N; i++) s_dispOptBtn[i] = nullptr;
    showSettingsMenu();
    if (old) lv_obj_delete(old);
}

static void dispOptCb(lv_event_t* e) {
    s_timeoutIdx = (int)(intptr_t)lv_event_get_user_data(e);
    saveTimeoutIdx();
    navigateBackFromDisplay();   // guardar + volver al menú de ajustes
}

static void dispBackCb(lv_event_t*) {
    navigateBackFromDisplay();
}

static void showDisplaySettings() {
    if (s_displayScr) return;

    lv_obj_t* scr = lv_obj_create(NULL);
    lv_obj_remove_style_all(scr);
    lv_obj_set_style_bg_color(scr, lv_color_hex(C_BG),  LV_PART_MAIN);
    lv_obj_set_style_bg_opa (scr, LV_OPA_COVER,          LV_PART_MAIN);
    lv_obj_clear_flag(scr, (lv_obj_flag_t)LV_OBJ_FLAG_SCROLLABLE);
    s_displayScr = scr;

    lv_obj_t* topBar = lv_obj_create(scr);
    lv_obj_remove_style_all(topBar);
    lv_obj_set_pos(topBar, 0, 0);
    lv_obj_set_size(topBar, 320, Y_TOP_H);
    lv_obj_set_style_bg_color(topBar, lv_color_hex(C_TOPBAR), LV_PART_MAIN);
    lv_obj_set_style_bg_opa (topBar, LV_OPA_COVER,             LV_PART_MAIN);
    lv_obj_clear_flag(topBar, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));

    lv_obj_t* backBtn = makeBtn(topBar, 2, 2, 64, 24, LV_SYMBOL_LEFT " Volver", dispBackCb);
    lv_obj_set_style_bg_color(backBtn, lv_color_hex(C_TOPBAR), LV_PART_MAIN);

    lv_obj_t* ttl = lv_label_create(topBar);
    lv_obj_set_style_text_font(ttl, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(ttl, lv_color_white(), LV_PART_MAIN);
    lv_label_set_text(ttl, "PANTALLA");
    lv_obj_align(ttl, LV_ALIGN_CENTER, 0, 0);

    makeSep(scr, 0, Y_SEP1, 320, 1);
    makeSecLabel(scr, 8, Y_CONT + 4, "Apagado de pantalla");

    const int bx = 8, bw = 304, bh = 34, bgap = 4;
    int by = Y_CONT + 24;
    for (int i = 0; i < TIMEOUT_N; i++) {
        s_dispOptBtn[i] = makeBtn(scr, bx, by, bw, bh,
                                   TIMEOUT_LABEL[i], dispOptCb,
                                   (void*)(intptr_t)i);
        by += bh + bgap;
    }
    refreshDisplayOpts();
    lv_screen_load(scr);
}

// ═══════════════════════════════════════════════════════════════════════════
// Menú de configuración principal
// ═══════════════════════════════════════════════════════════════════════════
static void settingsBackCb(lv_event_t*) {
    lv_obj_t* old = s_settingsScr;
    s_settingsScr = nullptr;
    lv_screen_load(s_scr);
    if (old) lv_obj_delete(old);
}

static void wifiConfigCb(lv_event_t*) {
    lv_obj_t* old = s_settingsScr;
    s_settingsScr = nullptr;
    s_navRequest  = CydNavRequest::WifiSetup;
    lv_screen_load(s_scr);
    if (old) lv_obj_delete(old);
}

static void mqttConfigCb(lv_event_t*) {
    lv_obj_t* old = s_settingsScr;
    s_settingsScr = nullptr;
    s_navRequest  = CydNavRequest::MqttSetup;
    lv_screen_load(s_scr);
    if (old) lv_obj_delete(old);
}

static void displayConfigCb(lv_event_t*) {
    lv_obj_t* old = s_settingsScr;
    s_settingsScr = nullptr;
    showDisplaySettings();
    if (old) lv_obj_delete(old);
}

static void showSettingsMenu() {
    if (s_settingsScr) return;

    lv_obj_t* scr = lv_obj_create(NULL);
    lv_obj_remove_style_all(scr);
    lv_obj_set_style_bg_color(scr, lv_color_hex(C_BG),  LV_PART_MAIN);
    lv_obj_set_style_bg_opa (scr, LV_OPA_COVER,          LV_PART_MAIN);
    lv_obj_clear_flag(scr, (lv_obj_flag_t)LV_OBJ_FLAG_SCROLLABLE);
    s_settingsScr = scr;

    lv_obj_t* topBar = lv_obj_create(scr);
    lv_obj_remove_style_all(topBar);
    lv_obj_set_pos(topBar, 0, 0);
    lv_obj_set_size(topBar, 320, Y_TOP_H);
    lv_obj_set_style_bg_color(topBar, lv_color_hex(C_TOPBAR), LV_PART_MAIN);
    lv_obj_set_style_bg_opa (topBar, LV_OPA_COVER,             LV_PART_MAIN);
    lv_obj_clear_flag(topBar, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));

    lv_obj_t* backBtn = makeBtn(topBar, 2, 2, 64, 24, LV_SYMBOL_LEFT " Volver", settingsBackCb);
    lv_obj_set_style_bg_color(backBtn, lv_color_hex(C_TOPBAR), LV_PART_MAIN);

    lv_obj_t* ttl = lv_label_create(topBar);
    lv_obj_set_style_text_font(ttl, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(ttl, lv_color_white(), LV_PART_MAIN);
    lv_label_set_text(ttl, "CONFIGURACION");
    lv_obj_align(ttl, LV_ALIGN_CENTER, 0, 0);

    makeSep(scr, 0, Y_SEP1, 320, 1);

    const int bx = 8, bw = 304, bh = 52, bgap = 10;
    int by = Y_CONT + 12;
    makeBtn(scr, bx, by,               bw, bh,
            LV_SYMBOL_WIFI     " WiFi Config",  wifiConfigCb);
    makeBtn(scr, bx, by +   (bh+bgap), bw, bh,
            LV_SYMBOL_LOOP     " MQTT Config",  mqttConfigCb);
    makeBtn(scr, bx, by + 2*(bh+bgap), bw, bh,
            LV_SYMBOL_SETTINGS " Pantalla",     displayConfigCb);

    lv_screen_load(scr);
}

static void gearCb(lv_event_t*) { showSettingsMenu(); }

// ═══════════════════════════════════════════════════════════════════════════
// API pública: navegación y recarga de pantalla
// ═══════════════════════════════════════════════════════════════════════════
CydNavRequest cydGetNavRequest()   { return s_navRequest; }
void          cydClearNavRequest() { s_navRequest = CydNavRequest::None; }

void cydReloadScreen() {
    // Llamar tras runWifiSetup / runMqttSetup para restaurar la pantalla principal.
    if (s_wakeOverlay) { lv_obj_delete(s_wakeOverlay); s_wakeOverlay = nullptr; }
    s_screenOff = false;
    blFadeTo(1.0f);
    if (s_scr) lv_screen_load(s_scr);
}

// ═══════════════════════════════════════════════════════════════════════════
// cydDisplayInit
// ═══════════════════════════════════════════════════════════════════════════
void cydDisplayInit(TTempSetting*   roomSetpoint,
                    TBoilerSetting* waterSetpoint,
                    TOnOffSetting*  heatingOn,
                    TFanSetting*    fanMode) {
    s_roomSp  = roomSetpoint;
    s_waterSp = waterSetpoint;
    s_heatOn  = heatingOn;
    s_fanMode = fanMode;

    loadTimeoutIdx();

    // ── Splash 2 s ───────────────────────────────────────────────────────
    showSplash(2000);

    // ── Pantalla principal ───────────────────────────────────────────────
    s_scr = lv_obj_create(NULL);
    lv_obj_remove_style_all(s_scr);
    lv_obj_set_style_bg_color(s_scr, lv_color_hex(C_BG), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(s_scr, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_clear_flag(s_scr, (lv_obj_flag_t)(LV_OBJ_FLAG_SCROLLABLE));
    lv_screen_load(s_scr);

    // ── Barra superior ───────────────────────────────────────────────────
    lv_obj_t* topBar = lv_obj_create(s_scr);
    lv_obj_remove_style_all(topBar);
    lv_obj_set_pos(topBar, 0, 0);
    lv_obj_set_size(topBar, 320, Y_TOP_H);
    lv_obj_set_style_bg_color(topBar, lv_color_hex(C_TOPBAR), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(topBar, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_clear_flag(topBar, (lv_obj_flag_t)(LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE));

    // Icono tint (izquierda) — parpadea cuando el boiler está calentando
    s_aguaLbl = lv_label_create(topBar);
    lv_obj_set_style_text_font(s_aguaLbl, &symbols_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_aguaLbl, lv_color_hex(0xaaccff), LV_PART_MAIN);
    lv_label_set_text(s_aguaLbl, MY_SYMBOL_TINT);
    lv_obj_set_pos(s_aguaLbl, 5, 7);

    // Icono llama — parpadea cuando la calefacción está activa
    s_fireLbl = lv_label_create(topBar);
    lv_obj_set_style_text_font(s_fireLbl, &symbols_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_fireLbl, lv_color_hex(0xff8844), LV_PART_MAIN);
    lv_label_set_text(s_fireLbl, MY_SYMBOL_FIRE);
    lv_obj_set_pos(s_fireLbl, 22, 7);

    // Temperatura interior + exterior juntas tras los iconos de estado
    s_ambLbl = lv_label_create(topBar);
    lv_obj_set_style_text_font(s_ambLbl, &symbols_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_ambLbl, lv_color_hex(0xaaccff), LV_PART_MAIN);
    lv_label_set_text(s_ambLbl, MY_SYMBOL_THERMOMETER " -- \xc2\xb0""C");
    lv_obj_set_pos(s_ambLbl, 44, 7);

    // Temperatura exterior (AM2301 en P3 IO22) — mismo font que interior para tamaño idéntico
    s_extLbl = lv_label_create(topBar);
    lv_obj_set_style_text_font(s_extLbl, &symbols_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_extLbl, lv_color_hex(0xffcc88), LV_PART_MAIN);
    lv_label_set_text(s_extLbl, MY_SYMBOL_THERM_EXT " " MY_SYMBOL_CHEVRON_R " --\xc2\xb0""C");
    lv_obj_set_pos(s_extLbl, 122, 7);
    lv_obj_clear_flag(s_extLbl, LV_OBJ_FLAG_CLICKABLE);

    auto makeStatusIcon = [&](int x, const char* sym, uint32_t col) -> lv_obj_t* {
        lv_obj_t* lbl = lv_label_create(topBar);
        lv_obj_set_style_text_font(lbl, &lv_font_montserrat_14, LV_PART_MAIN);
        lv_obj_set_style_text_color(lbl, lv_color_hex(col), LV_PART_MAIN);
        lv_label_set_text(lbl, sym);
        lv_obj_set_pos(lbl, x, 6);
        lv_obj_clear_flag(lbl, LV_OBJ_FLAG_CLICKABLE);
        return lbl;
    };
    // Botón engranaje — desplazado a x=222 para dejar hueco al label exterior
    lv_obj_t* gearBtn = makeBtn(topBar, 222, 2, 24, 24, LV_SYMBOL_SETTINGS, gearCb);
    lv_obj_set_style_bg_color(gearBtn, lv_color_hex(C_TOPBAR), LV_PART_MAIN);

    s_wifiDot = makeStatusIcon(250, LV_SYMBOL_WIFI,    C_WIFI_NO);
    s_mqttDot = makeStatusIcon(272, LV_SYMBOL_LOOP,    C_MQTT_DIS);
    s_linDot  = makeStatusIcon(296, LV_SYMBOL_SHUFFLE, C_WIFI_NO);

    // ── Separadores ──────────────────────────────────────────────────────
    makeSep(s_scr, 0,     Y_SEP1, 320, 1);    // horizontal top
    makeSep(s_scr, X_DIV, Y_CONT, 1, CONT_H); // vertical (x=154)
    makeSep(s_scr, 0,     Y_SEP2, 320, 1);    // horizontal bottom

    // ════════════════════════════════════════════════════════════════════
    // PANEL IZQUIERDO — CALEFACCIÓN
    // ════════════════════════════════════════════════════════════════════
    // Ancho de contenido: W_L - 8 = 146px  (margen 4px a cada lado)
    const int lx = 4;               // margen izquierdo
    const int lw = W_L - 8;         // 146px

    makeSecLabel(s_scr, lx, Y_CONT + 2, "CALEFACCION");

    s_heatBtn = makeBtn(s_scr, lx, Y_CONT + 20, lw, 36,
                        "APAGADO", heatCb, nullptr, &s_heatBtnLbl);
    lv_obj_set_style_text_font(s_heatBtnLbl, &lv_font_montserrat_14, LV_PART_MAIN);

    // Fila de setpoint (oculta cuando calefacción OFF)
    s_spRow = makeRow(s_scr, lx, Y_CONT + 62, lw, 35);
    lv_obj_add_flag(s_spRow, LV_OBJ_FLAG_HIDDEN);

    makeBtn(s_spRow, 0, 0, 36, 35, LV_SYMBOL_DOWN, spDownCb);

    s_spLbl = lv_label_create(s_spRow);
    lv_obj_set_style_text_font(s_spLbl, &lv_font_montserrat_20, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_spLbl, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_align(s_spLbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
    lv_obj_set_size(s_spLbl, 70, 35);
    lv_obj_set_pos(s_spLbl, 38, 10);
    lv_label_set_text(s_spLbl, "20.0\xc2\xb0""C");

    makeBtn(s_spRow, lw - 36, 0, 36, 35, LV_SYMBOL_UP, spUpCb);

    // ── Ventilador ───────────────────────────────────────────────────────
    makeSecLabel(s_scr, lx, Y_CONT + 99, "VENTILADOR");

    // Fila modo calefacción: Eco | Alto  (sin Apag., visible cuando heat ON)
    // Ancho 146px: 2 × 71px + 1 × 4px gap = 146px
    const int fwh = (lw - 4) / 2;   // ≈ 71px
    s_fanHeatingRow = makeRow(s_scr, lx, Y_CONT + 115, lw, 28);
    for (int i = 0; i < FAN_HEAT_N; i++) {
        s_fanBtn[i] = makeBtn(s_fanHeatingRow, i * (fwh + 4), 0, fwh, 28,
                               FAN_LAB[i], fanHeatCb, (void*)(intptr_t)i);
    }

    // Fila modo apagado: On | Off  (visible cuando heat OFF)
    // Ancho 146px: 2 × 68px + 10px gap = 146px
    const int fwo = (lw - 10) / 2;  // 68px
    s_fanOffRow = makeRow(s_scr, lx, Y_CONT + 115, lw, 28);
    lv_obj_add_flag(s_fanOffRow, LV_OBJ_FLAG_HIDDEN);
    s_fanOffBtn = makeBtn(s_fanOffRow, 0,         0, fwo, 28, "Off", fanOffCb);
    s_fanOnBtn  = makeBtn(s_fanOffRow, fwo + 10,  0, fwo, 28, "On",  fanOnCb);

    // Fila de nivel 1-10: ↓ | N | ↑  (visible cuando heat OFF + ventilación On)
    // Ancho 146px: 36 + 2 + 70 + 2 + 36 = 146px
    s_fanLevelRow = makeRow(s_scr, lx, Y_CONT + 144, lw, 28);
    lv_obj_add_flag(s_fanLevelRow, LV_OBJ_FLAG_HIDDEN);
    makeBtn(s_fanLevelRow, 0, 0, 36, 28, LV_SYMBOL_DOWN, fanLevelDownCb);

    s_fanLevelLbl = lv_label_create(s_fanLevelRow);
    lv_obj_set_style_text_font(s_fanLevelLbl, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_fanLevelLbl, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_text_align(s_fanLevelLbl, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
    lv_obj_set_size(s_fanLevelLbl, 70, 28);
    lv_obj_set_pos(s_fanLevelLbl, 38, 7);
    lv_label_set_text(s_fanLevelLbl, "5");

    makeBtn(s_fanLevelRow, 110, 0, 36, 28, LV_SYMBOL_UP, fanLevelUpCb);

    // ════════════════════════════════════════════════════════════════════
    // PANEL DERECHO — AGUA CALIENTE
    // ════════════════════════════════════════════════════════════════════
    // Ancho de contenido: W_R - 4 = 161px  (margen 2px)
    const int rx = X_R + 2;         // x=157
    const int rw = W_R - 4;         // 161px

    makeSecLabel(s_scr, rx, Y_CONT + 2, "AGUA CALIENTE");

    // 4 botones caldera en rejilla 2×2
    // Ancho botón: (161 - 9) / 2 = 76px  gap=9px
    const int bw = (rw - 9) / 2;    // 76px
    int bx[4] = {rx,      rx + bw + 9, rx,      rx + bw + 9};
    int by[4] = {Y_CONT + 20, Y_CONT + 20, Y_CONT + 62, Y_CONT + 62};
    for (int i = 0; i < BOILER_N; i++) {
        s_boilerBtn[i] = makeBtn(s_scr, bx[i], by[i], bw, 38,
                                  BOILER_LAB[i], boilerCb, (void*)(intptr_t)i);
    }

    // ── Energía — oculto (Combi D, sin opción eléctrica) ─────────────────
    lv_obj_add_flag(makeSecLabel(s_scr, rx, Y_CONT + 108, "ENERGIA"), LV_OBJ_FLAG_HIDDEN);

    s_energyDd = lv_dropdown_create(s_scr);
    lv_obj_set_pos(s_energyDd, rx, Y_CONT + 124);
    lv_obj_set_size(s_energyDd, rw, 28);
    lv_dropdown_set_options(s_energyDd, ENERGY_OPTS);
    lv_dropdown_set_selected(s_energyDd, 0);

    // Estilo oscuro para el dropdown
    lv_obj_set_style_bg_color(s_energyDd,     lv_color_hex(C_BTN_OFF), LV_PART_MAIN);
    lv_obj_set_style_text_color(s_energyDd,   lv_color_white(),         LV_PART_MAIN);
    lv_obj_set_style_border_color(s_energyDd, lv_color_hex(C_SEP),      LV_PART_MAIN);
    lv_obj_set_style_border_width(s_energyDd, 1,                         LV_PART_MAIN);
    lv_obj_set_style_text_font(s_energyDd,    &lv_font_montserrat_14,    LV_PART_MAIN);

    // Estilo de la lista desplegable
    lv_obj_t* ddList = lv_dropdown_get_list(s_energyDd);
    lv_obj_set_style_bg_color(ddList,     lv_color_hex(C_BTN_OFF), LV_PART_MAIN);
    lv_obj_set_style_text_color(ddList,   lv_color_white(),         LV_PART_MAIN);
    lv_obj_set_style_border_color(ddList, lv_color_hex(C_SEP),      LV_PART_MAIN);
    lv_obj_set_style_text_font(ddList,    &lv_font_montserrat_14,    LV_PART_MAIN);

    lv_obj_add_event_cb(s_energyDd, energyDdCb, LV_EVENT_VALUE_CHANGED, nullptr);
    lv_obj_add_flag(s_energyDd, LV_OBJ_FLAG_HIDDEN);

    // ── Barra de estado ───────────────────────────────────────────────────
    s_statusLbl = lv_label_create(s_scr);
    lv_obj_set_style_text_font(s_statusLbl, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_statusLbl, lv_color_hex(C_WIFI_OK), LV_PART_MAIN);
    lv_label_set_text(s_statusLbl, "Iniciando...");
    lv_obj_align(s_statusLbl, LV_ALIGN_BOTTOM_LEFT, 5, -18);

    s_ipLbl = lv_label_create(s_scr);
    lv_obj_set_style_text_font(s_ipLbl, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_set_style_text_color(s_ipLbl, lv_color_hex(0x88aaff), LV_PART_MAIN);
    lv_label_set_text(s_ipLbl, "");
    lv_obj_align(s_ipLbl, LV_ALIGN_BOTTOM_LEFT, 5, -2);

    refreshControls();
    placeLogoInStatusBar(s_scr);

    // ── Tarea de fade de backlight ────────────────────────────────────────
    xTaskCreatePinnedToCore(backlightTask, "bckl", 1536, nullptr, 1, nullptr, 1);
}

// ═══════════════════════════════════════════════════════════════════════════
// cydDisplayUpdate  — llamar en cada iteración de loop()
// ═══════════════════════════════════════════════════════════════════════════
void cydDisplayUpdate(bool wifiok, bool mqttok, bool trumaok,
                      bool truma_reset, bool inota, bool mqttEnabled,
                      float roomTemp, float waterTemp, bool waterHeating,
                      float extTemp) {

    // ── Apagado automático de pantalla ───────────────────────────────────
    // Tres estados: brillo 100 % → aviso 50 % (5 s antes) → apagado.
    // Un toque restablece el brillo y reinicia la cuenta porque LVGL
    // resetea lv_display_get_inactive_time() con cualquier evento de entrada.
    {
        uint32_t to       = TIMEOUT_MS[s_timeoutIdx];
        uint32_t inactive = lv_display_get_inactive_time(NULL);

        if (to > 0 && !s_screenOff) {
            if (inactive >= to) {
                // ── Apagar ────────────────────────────────────────────────
                blFadeTo(0.0f);
                s_screenOff    = true;
                s_screenDimmed = false;
                if (!s_wakeOverlay) {
                    // Overlay transparente en lv_layer_top — captura el primer
                    // toque y enciende la pantalla sin activar botones debajo.
                    s_wakeOverlay = lv_obj_create(lv_layer_top());
                    lv_obj_remove_style_all(s_wakeOverlay);
                    lv_obj_set_size(s_wakeOverlay, 320, 240);
                    lv_obj_set_pos(s_wakeOverlay, 0, 0);
                    lv_obj_set_style_bg_opa(s_wakeOverlay, LV_OPA_TRANSP, LV_PART_MAIN);
                    lv_obj_add_event_cb(s_wakeOverlay, wakeCb, LV_EVENT_PRESSED, nullptr);
                }
            } else if (inactive + 5000 >= to) {
                // ── Aviso: quedan ≤ 5 s ──────────────────────────────────
                if (!s_screenDimmed) {
                    blFadeTo(0.3f);
                    s_screenDimmed = true;
                }
            } else {
                // ── Brillo normal (o recuperación tras toque en aviso) ────
                if (s_screenDimmed) {
                    blFadeTo(1.0f);
                    s_screenDimmed = false;
                }
            }
        }
    }

    // ── Indicadores de estado (iconos barra superior) ────────────────────
    {
        bool blinkPhase = (millis() % 1000) < 500;
        // Tint: parpadea mientras el boiler calienta
        if (s_aguaLbl) {
            bool vis = !waterHeating || blinkPhase;
            lv_obj_set_style_text_color(s_aguaLbl,
                vis ? lv_color_hex(0xaaccff) : lv_color_hex(C_TOPBAR),
                LV_PART_MAIN);
        }
        // Llama: parpadea mientras la calefacción está activada
        if (s_fireLbl) {
            bool heatActive = s_heatOn && (s_heatOn->getIntValue() != 0);
            bool vis = !heatActive || blinkPhase;
            lv_obj_set_style_text_color(s_fireLbl,
                vis ? lv_color_hex(0xff8844) : lv_color_hex(C_TOPBAR),
                LV_PART_MAIN);
        }
    }
    if (s_ambLbl) {
        char buf[32];
        if (trumaok && roomTemp > -200.0f)
            snprintf(buf, sizeof(buf), MY_SYMBOL_THERMOMETER " %.1f \xc2\xb0""C", roomTemp);
        else
            strcpy(buf, MY_SYMBOL_THERMOMETER " -- \xc2\xb0""C");
        lv_label_set_text(s_ambLbl, buf);
    }

    // ── Temperatura exterior (AM2301) ────────────────────────────────────
    if (s_extLbl) {
        char buf[28];
        if (extTemp > -200.0f)
            snprintf(buf, sizeof(buf), MY_SYMBOL_THERM_EXT " " MY_SYMBOL_CHEVRON_R " %.1f\xc2\xb0""C", extTemp);
        else
            strcpy(buf, MY_SYMBOL_THERM_EXT " " MY_SYMBOL_CHEVRON_R " --\xc2\xb0""C");
        lv_label_set_text(s_extLbl, buf);
    }

    // ── Icono WiFi ───────────────────────────────────────────────────────
    static bool s_everConnected = false;
    if (wifiok) s_everConnected = true;
    if (s_wifiDot) {
        lv_color_t c = lv_color_hex(wifiok          ? C_WIFI_OK   :
                                     s_everConnected ? C_WIFI_NO   :
                                                       C_WIFI_CONN);
        lv_obj_set_style_text_color(s_wifiDot, c, LV_PART_MAIN);
    }

    // ── Icono MQTT ───────────────────────────────────────────────────────
    if (s_mqttDot) {
        lv_color_t c = lv_color_hex(!mqttEnabled ? C_MQTT_DIS :
                                     mqttok       ? C_MQTT_OK  : C_MQTT_NO);
        lv_obj_set_style_text_color(s_mqttDot, c, LV_PART_MAIN);
    }

    // ── Icono LIN bus ────────────────────────────────────────────────────
    if (s_linDot) {
        lv_obj_set_style_text_color(s_linDot,
            lv_color_hex(trumaok ? C_WIFI_OK : C_WIFI_NO), LV_PART_MAIN);
    }

    // ── IP ───────────────────────────────────────────────────────────────
    if (s_ipLbl) {
        lv_label_set_text(s_ipLbl, wifiok ? WiFi.localIP().toString().c_str() : "");
    }

    // ── Mensaje de estado ────────────────────────────────────────────────
    const char* msg  = "";
    uint32_t    msgC = C_WIFI_OK;
    if (inota) {
        msg = "Actualizando firmware...";  msgC = 0xffd700;
    } else if (!wifiok) {
        if (WiFi.status() == WL_DISCONNECTED || WiFi.status() == WL_IDLE_STATUS) {
            msg = "Conectando WiFi...";    msgC = C_WIFI_CONN;
        } else {
            msg = "Sin WiFi";              msgC = C_WIFI_NO;
        }
    } else if (!mqttok && mqttEnabled) {
        msg = "Sin MQTT";                  msgC = C_MQTT_NO;
    } else if (!trumaok) {
        msg = LV_SYMBOL_WARNING " Sin LIN bus"; msgC = C_WIFI_NO;
    }

    if (s_statusLbl) {
        lv_label_set_text(s_statusLbl, msg);
        lv_obj_set_style_text_color(s_statusLbl, lv_color_hex(msgC), LV_PART_MAIN);
    }

    // ── Refresco de controles (pueden cambiar por MQTT externo) ──────────
    refreshControls();
}

#endif // CYD
