/*
 * symbols_14.c — generated by scripts/gen_symbols.py  DO NOT EDIT
 * Glyphs : U+F043 fa-tint, U+F2C7 fa-thermometer-half
 * Size   : 14px   BPP: 4
 */

#include "lvgl.h"

// symbols_14 → lv_font_montserrat_14 (fallback para caracteres normales)
LV_FONT_DECLARE(lv_font_montserrat_14);

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+F043  fa-tint */
    0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0xeb, 0x00, 0x00, 0x00, 0x05, 0xff, 0x10, 0x00, 0x00,
    0x0d, 0xff, 0x80, 0x00, 0x00, 0x6f, 0xff, 0xf2, 0x00, 0x01, 0xef, 0xff, 0xfb, 0x00, 0x0a, 0xff,
    0xff, 0xff, 0x60, 0x4f, 0xff, 0xff, 0xff, 0xf1, 0xbf, 0xff, 0xff, 0xff, 0xf7, 0xff, 0xbf, 0xff,
    0xff, 0xfa, 0xff, 0x2f, 0xff, 0xff, 0xfa, 0xbf, 0x58, 0xff, 0xff, 0xf7, 0x4f, 0xf6, 0x2c, 0xff,
    0xe1, 0x07, 0xff, 0xff, 0xfe, 0x30, 0x00, 0x3a, 0xcc, 0x81, 0x00,
    /* U+F2C7  fa-thermometer-half */
    0x00, 0x01, 0x00, 0x00, 0x04, 0xef, 0xe4, 0x00, 0x0e, 0x77, 0xde, 0x00, 0x3b, 0xdf, 0x9f, 0x30,
    0x3b, 0xdf, 0x9f, 0x30, 0x3b, 0xdf, 0x9f, 0x30, 0x3b, 0xdf, 0x9f, 0x30, 0x3b, 0xdf, 0x9f, 0x30,
    0x3b, 0xdf, 0x9f, 0x30, 0x6a, 0xdf, 0x7f, 0x60, 0xda, 0xff, 0x79, 0xd0, 0xfd, 0xff, 0xd3, 0xf0,
    0xdd, 0xff, 0x86, 0xd0, 0x5f, 0xa7, 0x6f, 0x50, 0x05, 0xdf, 0xd5, 0x00,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index =     0, .adv_w =  160, .box_w =  10, .box_h =  15, .ofs_x =   0, .ofs_y =  -2},  /* U+F043 */
    {.bitmap_index =    75, .adv_w =  112, .box_w =   7, .box_h =  15, .ofs_x =   0, .ofs_y =  -2},  /* U+F2C7 */
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {  /* U+F043  fa-tint */
        .range_start = 0xF043, .range_length = 1, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {  /* U+F2C7  fa-thermometer-half */
        .range_start = 0xF2C7, .range_length = 1, .glyph_id_start = 2,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
};

static lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc    = glyph_dsc,
    .cmaps        = cmaps,
    .kern_dsc     = NULL,
    .kern_scale   = 0,
    .cmap_num     = 2,
    .bpp          = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t symbols_14 = {
    .get_glyph_dsc    = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height      = 14,
    .base_line        = 3,
    .subpx            = LV_FONT_SUBPX_NONE,
    .underline_position  = -1,
    .underline_thickness = 1,
    .dsc              = &font_dsc,
    .fallback         = &lv_font_montserrat_14,
    .user_data        = NULL,
};
